name: ExampleParameterTuning
goal: MAXIMIZE
max_trials: 10
max_parallel_trials: 1
script: examples/train.py
params:
        - parameterName: number
          type: DOUBLE
          minValue: 1.e-4
          maxValue: 1.e-1
          scaleType: UNIT_LOG_SCALE
        - parameterName: category
          type: CATEGORICAL
          categoricalValues:
                  - HOME
                  - WORK
                  - BEACH
