name: ExampleParameterTuning
goal: MAXIMIZE
maxTrials: 10
maxParallelTrials: 1
params:
        - parameterName: number
          type: DOUBLE
          minValue: 1.e-4
          maxValue: 1.e-1
          scaleType: UNIT_LOG_SCALE
        - parameterName: category
          type: CATEGORICAL
          categoricalValues:
                  - HOME
                  - WORK
                  - BEACH

# DIVERGED FROM CLOUD ML.
launcher: python  # Can use a python interpreter from a virtual env.
script: examples/train.py
maxTrialTime: 10s
